# -*- coding: utf-8 -*-
"""Baitaptrenlop.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MGyv-oVntflhuPXp0D1OCutmI2xes-Wc
"""

#bai 1
a=int(input("Nhap so a:"))
b=int(input("Nhap so b:"))
tong=a+b
hieu=a-b
tich=a*b
thuong=a/b
print(f"Tong:{tong} || Hieu:{hieu} || Tich:{tich} || Thuong:{thuong}")

#bai 2
text=str("Hello World")
temp=text[2:5]
print(temp)

#bai 3
s="Hello World"
s_trimmed=s.strip()
print(f"Xóa khoảng trắng:'{s_trimmed}'")

print(f"Dạng hoa: {s_trimmed.upper()}")
print(f"Dạng thường: {s_trimmed.lower()}")

s_replaced =s_trimmed.replace("H","J")
print(f"Thay H thành J: {s_replaced}")

#bai 4
a=int(input("Nhap so a:"))
b=int(input("Nhap so b:"))
if a>b:
  print("Hello World!")

#bai 5
if a==b:
  print("Yes")
else:
  print("No")

#bai 6
a=int(input("Nhap so a:"))
b=int(input("Nhap so b:"))
if a==b:
  print("1")
  if a>b:
    print("2")
else : print("3")

#bai 7
a=int(input("Nhap so a:"))
b=int(input("Nhap so b:"))
c=int(input("Nhap so c:"))
d=int(input("Nhap so d:"))
if a==b and b==d:
    print("Hello World")

#bai 8
if a==b or c==d:
    print("Hello World")

#bai 9
print('Yes') if a>b else print('No')

#bai 10
a=int(input("Nhap so a:"))
b=int(input("Nhap so b:"))
print("A") if a > b else print("=") if a == b else print("B")

#bai 11
def mangA():
  a=[]
  n=input("Nhap so luong phan tu:")
  for i in range(n):
    value=int(input("Nhap phan tu:"))
    a.append(value)
  return a
def mangB():
  b=[]
  n=input("Nhap so luong phan tu:")
  for i in range(n):
    value=int(input("Nhap phan tu:"))
    if value%2==0:
      b.append(value)
  return b

#bai 12
def mang():
  tong=0
  for i in range(1000):
    if i % 3 == 0 or i % 5 == 0:
      tong += i
  print(f"Tổng từ 0 đến 999 mà là bội của 3 và 5 là {tong}")

#bai 13
def tron_mang(a, b):
    res = []

    min_len = min(len(a), len(b))

    for i in range(min_len):
        res.append(a[i] + b[i])


    if len(a) > len(b):
        res.extend(a[min_len:])
    else:
        res.extend(b[min_len:])

    return res


mang_a = [3, 9, 1, 4]
mang_b = [2, 7, 4, 3, 2, 8]
print(f"Kết quả trộn: {tron_mang(mang_a, mang_b)}")

#bai 14
import random

# a. Tạo mảng a chứa số nguyên ngẫu nhiên
def tao_mang(m, n):
    a = []
    for i in range(m):
        row = []
        for j in range(n):
            row.append(random.randint(0, 10))  # số từ 0 -> 10
        a.append(row)
    return a

# b. Xuất dòng k
def xuat_dong(a, k):
    if 0 <= k < len(a):
        print(f"Dòng {k} : {a[k]}")
    else:
        print(f"Dòng {k} không hợp lệ. Mảng chỉ có {len(a)} dòng.")

# c. Xuất cột k
def xuat_cot(a, k):
    if not a:
        print("Mảng rỗng, không có cột để xuất.")
        return
    if not a[0]:
        print("Mảng không có cột để xuất.")
        return
    if 0 <= k < len(a[0]):
        print(f"Cột {k} :")
        for i in range(len(a)):
            print(a[i][k], end=" ")
        print()
    else:
        print(f"Cột {k} không hợp lệ. Mảng chỉ có {len(a[0])} cột.")

# d. Tìm dòng có tổng >= 45
def tim_dong(a):
    if not a:
        print("Mảng rỗng, không có dòng để kiểm tra.")
        return
    found = False
    print("Tìm dòng có tổng >= 45:")
    for i in range(len(a)):
        if sum(a[i]) >= 45:
            print(f"Dòng {i} có tổng >= 45: {a[i]}")
            found = True
    if not found:
        print("Không tìm thấy dòng nào có tổng >= 45.")

# e. Tìm cột có tích nhỏ nhất
def cot_tich_nho_nhat(a):
    if not a or not a[0]:
        print("Mảng rỗng hoặc không có cột để tính tích.")
        return

    m = len(a)
    n = len(a[0])
    min_tich = None
    cot_min = -1

    for j in range(n):
        tich = 1
        for i in range(m):
            tich *= a[i][j]
        if min_tich is None or tich < min_tich:
            min_tich = tich
            cot_min = j

    if cot_min != -1:
        print(f"Cột có tích nhỏ nhất: {cot_min} với tích là {min_tich}")
    else:
        print("Không tìm thấy cột nào.")

# f. Xuất phần tử dòng chẵn, cột lẻ
def dong_chan_cot_le(a):
    if not a or not a[0]:
        print("Mảng rỗng hoặc không có phần tử để xuất (dòng chẵn, cột lẻ).")
        return

    print("Phần tử dòng chẵn, cột lẻ:")
    found_elements = False
    for i in range(len(a)):
        if i % 2 == 0: # Dòng chẵn (index 0, 2, ...)
            for j in range(len(a[0])):
                if j % 2 == 1: # Cột lẻ (index 1, 3, ...)
                    print(a[i][j], end=" ")
                    found_elements = True
    if found_elements:
        print()
    else:
        print("Không có phần tử dòng chẵn, cột lẻ phù hợp.")

# g. TBC các phần tử chẵn thuộc dòng lẻ
def tbc_chan_dong_le(a):
    if not a or not a[0]:
        print("Mảng rỗng hoặc không có phần tử để tính TBC (chẵn, dòng lẻ).")
        return

    tong = 0
    dem = 0
    for i in range(len(a)):
        if i % 2 == 1: # Dòng lẻ (index 1, 3, ...)
            for j in range(len(a[0])):
                if a[i][j] % 2 == 0: # Phần tử chẵn
                    tong += a[i][j]
                    dem += 1
    if dem > 0:
        print(f"TBC các phần tử chẵn thuộc dòng lẻ = {tong / dem}")
    else:
        print("Không có phần tử chẵn thuộc dòng lẻ phù hợp.")

# h. TBC các phần tử biên
def tbc_bien(a):
    if not a or not a[0]:
        print("Mảng rỗng hoặc không có phần tử để tính TBC biên.")
        return

    m = len(a)
    n = len(a[0])
    tong = 0
    dem = 0

    if m == 1 and n == 1: # Trường hợp đặc biệt 1x1
        tong = a[0][0]
        dem = 1
    elif m == 1: # Trường hợp 1xn
        for j in range(n):
            tong += a[0][j]
            dem += 1
    elif n == 1: # Trường hợp mx1
        for i in range(m):
            tong += a[i][0]
            dem += 1
    else:
        for i in range(m):
            for j in range(n):
                if i == 0 or i == m - 1 or j == 0 or j == n - 1:
                    tong += a[i][j]
                    dem += 1

    if dem > 0:
        print(f"TBC biên = {tong / dem}")
    else:
        print("Không có phần tử biên phù hợp để tính TBC.")

#########chạy thử######################
m = int(input("Nhập số dòng: "))
n = int(input("Nhập số cột: "))

a = tao_mang(m, n)

print("Mảng a:")
for row in a:
    print(row)

k = int(input("Nhập k: "))

xuat_dong(a, k)
xuat_cot(a, k)
tim_dong(a)
cot_tich_nho_nhat(a)
dong_chan_cot_le(a)
tbc_chan_dong_le(a)
tbc_bien(a)

#bai 15

# a. Xây dựng cấu trúc SINHVIEN
class SinhVien:
    def __init__(self, ma, ten, namsinh, dtb):
        self.ma = ma
        self.ten = ten
        self.namsinh = namsinh
        self.dtb = dtb


# b. Nhập danh sách sinh viên
def nhap_ds(n):
    ds = []
    for i in range(n):
        print(f"\nNhập sinh viên {i+1}:")
        ma = input("Mã SV (10 ký tự): ")
        ten = input("Tên (<=20 ký tự): ")
        namsinh = int(input("Năm sinh: "))
        dtb = float(input("Điểm TB: "))
        sv = SinhVien(ma, ten, namsinh, dtb)
        ds.append(sv)
    return ds


# c. Đếm sinh viên đủ điều kiện lên lớp (dtb >= 5)
def dem_len_lop(ds):
    dem = 0
    for sv in ds:
        if sv.dtb >= 5:
            dem += 1
    return dem


# d. Xuất sinh viên đủ 20 tuổi
def sv_20_tuoi(ds):
    nam_hien_tai = 2026  # bạn có thể sửa lại
    print("\nSinh viên đủ 20 tuổi:")
    for sv in ds:
        if nam_hien_tai - sv.namsinh == 20:
            print(sv.ten, "-", sv.ma)


# e. Đếm sinh viên hệ đại học (có "DH" ở vị trí 2,3)
def dem_he_dh(ds):
    dem = 0
    for sv in ds:
        if len(sv.ma) >= 4 and sv.ma[2:4] == "DH":
            dem += 1
    return dem


# f. Đếm sinh viên tên "Lan"
def dem_ten_lan(ds):
    dem = 0
    for sv in ds:
        if sv.ten.strip().split()[-1] == "Lan":
            dem += 1
    return dem


# g. Đếm sinh viên họ "Phan"
def dem_ho_phan(ds):
    dem = 0
    for sv in ds:
        if sv.ten.strip().split()[0] == "Phan":
            dem += 1
    return dem


# ================= CHẠY THỬ =================
n = int(input("Nhập số sinh viên: "))
ds = nhap_ds(n)

print("\nSố SV lên lớp:", dem_len_lop(ds))
sv_20_tuoi(ds)
print("Số SV hệ ĐH:", dem_he_dh(ds))
print("Số SV tên Lan:", dem_ten_lan(ds))
print("Số SV họ Phan:", dem_ho_phan(ds))