# -*- coding: utf-8 -*-
"""baitapvenha.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-x2pgruEdUUlL0lHgX9GWddoglyIXzc4
"""

#Bai 1
def tron_mang(a, b):
    c = []
    n = min(len(a), len(b))

    # lấy min từng phần tử
    for i in range(n):
        c.append(min(a[i], b[i]))

    # thêm phần dư
    if len(a) > len(b):
        c.extend(a[n:])
    else:
        c.extend(b[n:])

    return c


# test
a = [3, 9, 1, 4]
b = [2, 7, 4, 3, 2, 8]

print("Kết quả:", tron_mang(a, b))

#bai 2

def nhap_ma_tran(n):
    a = []
    for i in range(n):
        while True:
            try:
                row_str = input(f"Nhập {n} số cho dòng {i} (cách nhau bởi dấu cách): ")
                row = list(map(int, row_str.split()))
                if len(row) == n:
                    a.append(row)
                    break
                else:
                    print(f"Lỗi: Vui lòng nhập đúng {n} số.")
            except ValueError:
                print("Lỗi: Vui lòng nhập các số nguyên.")
    return a

#cau a
def tong_tam_giac_tren_cheo_phu(a, n):
    tong = 0
    for i in range(n):
        for j in range(n):
            if i + j <= n - 1:
                tong += a[i][j]
    return tong
#cau b
def doi_am(a):
    n = len(a)
    for i in range(n):
        for j in range(n):
            if a[i][j] < 0:
                a[i][j] = abs(a[i][j])
#cau c
def thay_chan(a, x):
    n = len(a)
    for i in range(n):
        for j in range(n):
            if a[i][j] % 2 == 0:
                a[i][j] = x
#cau d
def toan_chan(a):
    for row in a:
        for x in row:
            if x % 2 != 0:
                return False
    return True
#cau e
def doi_xung(a, n):
    for i in range(n):
        for j in range(n):
            if a[i][j] != a[j][i]:
                return False
    return True
#cau f
def cheo_chinh_tang(a, n):
    for i in range(n - 1):
        if a[i][i] > a[i+1][i+1]:
            return False
    return True
#cau g
def xuat_tam_giac_duoi(a, n):
    print("Tam giác dưới:")
    for i in range(n):
        for j in range(n):
            if i + j >= n - 1:
                print(a[i][j], end=" ")
        print()
#cau h
def cheo_phu_giam(a, n):
    for i in range(n - 1):
        if a[i][n-1-i] < a[i+1][n-2-i]:
            return False
    return True
#chay
n = int(input("Nhập n: "))
a = nhap_ma_tran(n)

print("Tổng tam giác trên:", tong_tam_giac_tren_cheo_phu(a, n))

doi_am(a)
print("Sau khi đổi âm:", a)

thay_chan(a, 0)
print("Sau khi thay chẵn:", a)

print("Toàn chẵn?", toan_chan(a))
print("Đối xứng?", doi_xung(a, n))
print("Chéo chính tăng?", cheo_chinh_tang(a, n))

xuat_tam_giac_duoi(a, n)

print("Chéo phụ giảm?", cheo_phu_giam(a, n))